// AUTO-GENERATED by MuMain/tools/gen_afk_spots_native.py — do not edit by hand.
// 数据源：config.MonsterSpawnArea + TerrainData，按【原生客户端】找怪半径
// iHuntingRange=6 (欧氏 R=9) 重算；与网页端离线幽灵(R=15)的 afkSpots.js 是两套。
#pragma once

struct AfkSpot
{
    int x;
    int y;
    int lv;        // 这一簇里最强怪的等级
    int lvMin;     // 最低怪等级
    const char* mons;  // 圈内怪数前 2，';' 分隔（英文）
};

struct AfkSpotList
{
    int world;            // ENUM_WORLD
    const AfkSpot* spots;
    int count;
};

static const AfkSpot AFK_SPOTS_W0[] = {
    { 203, 167, 4, 2, "Spider;Budge Dragon" },
    { 192, 90, 6, 2, "Budge Dragon;Spider" },
    { 143, 28, 6, 4, "Bull Fighter;Budge Dragon" },
    { 44, 19, 17, 9, "Giant;Hound" },
    { 103, 176, 19, 14, "Lich;Skeleton Warrior" },
    { 175, 192, 19, 2, "Lich;Skeleton Warrior" },
    { 95, 196, 19, 9, "Lich;Skeleton Warrior" },
    { 64, 83, 17, 9, "Hound;Elite Bull Fighter" },
};

static const AfkSpot AFK_SPOTS_W1[] = {
    { 175, 127, 38, 32, "Skeleton Archer;Hell Hound" },
    { 240, 9, 44, 32, "Ghost;Elite Skeleton" },
    { 49, 182, 32, 32, "Ghost" },
    { 241, 173, 34, 28, "Cyclops;Skeleton Archer" },
    { 46, 205, 28, 19, "Larva;Skeleton Warrior" },
    { 15, 113, 48, 44, "Dark Knight;Poison Bull" },
    { 79, 154, 32, 25, "Ghost;Larva" },
    { 42, 117, 55, 44, "Poison Bull;Gorgon" },
};

static const AfkSpot AFK_SPOTS_W2[] = {
    { 36, 24, 36, 22, "Elite Yeti;Hommerd" },
    { 200, 164, 36, 36, "Elite Yeti" },
    { 60, 132, 52, 22, "Elite Yeti;Ice Queen" },
    { 80, 136, 52, 22, "Elite Yeti;Ice Queen" },
    { 128, 28, 26, 20, "Worm;Hommerd" },
    { 136, 120, 36, 20, "Worm;Assassin" },
    { 124, 48, 26, 20, "Hommerd;Ice Monster" },
    { 120, 68, 26, 20, "Hommerd;Ice Monster" },
};

static const AfkSpot AFK_SPOTS_W3[] = {
    { 136, 24, 13, 3, "Goblin;Chain Scorpion" },
    { 128, 44, 13, 3, "Goblin;Chain Scorpion" },
    { 132, 128, 18, 3, "Goblin;Chain Scorpion" },
    { 227, 125, 18, 3, "Goblin;Chain Scorpion" },
    { 12, 132, 16, 8, "Elite Goblin;Agon" },
    { 32, 136, 16, 8, "Elite Goblin;Agon" },
    { 124, 192, 18, 8, "Elite Goblin;Agon" },
    { 52, 124, 16, 8, "Beetle Monster;Hunter" },
};

static const AfkSpot AFK_SPOTS_W4[] = {
    { 12, 99, 64, 62, "Death Knight;Death Gorgon" },
    { 33, 206, 66, 60, "Death Gorgon;Balrog" },
    { 103, 197, 57, 54, "Death Cow;Cursed Wizard" },
    { 238, 213, 54, 50, "Poison Shadow;Cursed Wizard" },
    { 195, 40, 50, 47, "Poison Shadow;Shadow" },
    { 30, 102, 64, 60, "Death Knight;Devil" },
    { 191, 244, 54, 47, "Poison Shadow;Shadow" },
    { 94, 100, 60, 57, "Devil;Death Cow" },
};

static const AfkSpot AFK_SPOTS_W7[] = {
    { 22, 230, 74, 68, "Lizard King;Hydra" },
    { 71, 140, 68, 66, "Silver Valkyrie;Great Bahamut" },
    { 78, 19, 45, 43, "Vepar;Bahamut" },
    { 226, 52, 70, 46, "Great Bahamut;Valkyrie" },
    { 46, 217, 70, 68, "Lizard King;Silver Valkyrie" },
    { 119, 20, 46, 45, "Vepar;Valkyrie" },
    { 227, 123, 70, 66, "Lizard King;Great Bahamut" },
    { 193, 52, 66, 46, "Great Bahamut;Valkyrie" },
};

static const AfkSpot AFK_SPOTS_W8[] = {
    { 165, 219, 93, 83, "Beam Knight;Tantallos" },
    { 81, 126, 84, 83, "Tantallos;Beam Knight" },
    { 11, 234, 90, 83, "Beam Knight;Tantallos" },
    { 134, 72, 76, 72, "Mutant;Bloody Wolf" },
    { 102, 61, 76, 76, "Bloody Wolf" },
    { 166, 190, 84, 84, "Beam Knight" },
    { 25, 127, 83, 83, "Tantallos" },
    { 27, 75, 80, 80, "Iron Wheel" },
};

static const AfkSpot AFK_SPOTS_W10[] = {
    { 71, 33, 78, 75, "Mega Crust;Alquamos" },
    { 18, 31, 75, 75, "Alquamos" },
    { 44, 221, 100, 96, "Great Drakan;Phantom Knight" },
    { 33, 111, 96, 92, "Alpha Crust;Phantom Knight" },
    { 32, 87, 92, 86, "Alpha Crust;Drakan" },
    { 55, 181, 100, 100, "Great Drakan" },
    { 93, 47, 78, 78, "Mega Crust" },
    { 55, 73, 86, 86, "Drakan" },
};

static const AfkSpot AFK_SPOTS_W33[] = {
    { 40, 224, 120, 114, "Bloody Witch Queen;Bloody Death Rider" },
    { 228, 60, 78, 74, "Death Rider;Forest Orc" },
    { 217, 36, 78, 72, "Death Rider;Death Tree" },
    { 230, 132, 84, 72, "Forest Orc;Death Tree" },
    { 190, 144, 84, 78, "Death Rider;Blue Golem" },
    { 24, 186, 120, 115, "Bloody Witch Queen;Bloody Golem" },
    { 194, 33, 78, 72, "Death Tree;Forest Orc" },
    { 158, 235, 117, 114, "Bloody Death Rider;Bloody Orc" },
};

static const AfkSpot AFK_SPOTS_W37[] = {
    { 137, 47, 100, 88, "Blade Hunter;Kentauros" },
    { 68, 28, 100, 98, "Berserker;Gigantis" },
    { 207, 40, 88, 85, "Satyros;Blade Hunter" },
    { 74, 162, 126, 123, "Berserker Warrior;Kentauros Warrior" },
    { 112, 98, 129, 128, "Gigantis Warrior;Genocider Warrior" },
    { 142, 127, 129, 126, "Kentauros Warrior;Genocider Warrior" },
    { 89, 124, 128, 123, "Kentauros Warrior;Berserker Warrior" },
    { 63, 101, 105, 100, "Berserker;Genocider" },
};

static const AfkSpot AFK_SPOTS_W38[] = {
    { 106, 154, 118, 118, "Persona" },
    { 97, 78, 118, 117, "Persona;Twin Tale" },
    { 162, 129, 119, 118, "Dreadfear;Persona" },
    { 105, 133, 119, 117, "Persona;Twin Tale" },
    { 128, 69, 118, 117, "Persona;Twin Tale" },
    { 197, 136, 117, 117, "Twin Tale" },
    { 153, 78, 117, 117, "Twin Tale" },
    { 177, 150, 119, 119, "Dreadfear" },
};

static const AfkSpot AFK_SPOTS_W51[] = {
    { 104, 196, 13, 4, "Strange Rabbit;Polluted Butterfly" },
    { 128, 28, 48, 19, "Hideous Rabbit;Werewolf" },
    { 204, 24, 48, 30, "Cursed Lich;Totem Golem" },
    { 64, 64, 24, 19, "Hideous Rabbit;Werewolf" },
    { 114, 130, 24, 4, "Strange Rabbit;Polluted Butterfly" },
    { 96, 128, 24, 4, "Strange Rabbit;Hideous Rabbit" },
    { 124, 112, 48, 19, "Hideous Rabbit;Werewolf" },
    { 132, 92, 48, 19, "Cursed Lich;Totem Golem" },
};

static const AfkSpot AFK_SPOTS_W56[] = {
    { 236, 80, 106, 98, "Shadow Pawn;Shadow Knight" },
    { 43, 118, 137, 131, "Ice Napin;Shadow Master" },
    { 232, 15, 100, 98, "Shadow Knight;Shadow Pawn" },
    { 52, 20, 104, 100, "Sapi-Tres;Shadow Knight" },
    { 178, 136, 137, 135, "Shadow Master;Ice Napin" },
    { 215, 150, 135, 131, "Sapi Queen;Ice Napin" },
    { 229, 202, 96, 95, "Sapi-Unus;Sapi-Duo" },
    { 33, 184, 107, 106, "Blaze Napin;Ghost Napin" },
};

static const AfkSpot AFK_SPOTS_W57[] = {
    { 33, 220, 148, 143, "Dark Giant;Dark Coolutin" },
    { 196, 104, 142, 102, "Iron Knight;Ice Walker" },
    { 98, 31, 148, 143, "Dark Iron Knight;Dark Giant" },
    { 136, 106, 142, 102, "Coolutin;Ice Giant" },
    { 171, 207, 112, 102, "Giant Mammoth;Ice Walker" },
    { 166, 187, 122, 122, "Ice Giant" },
    { 117, 42, 145, 143, "Dark Coolutin;Dark Giant" },
    { 207, 26, 142, 132, "Iron Knight;Coolutin" },
};

static const AfkSpot AFK_SPOTS_W63[] = {
    { 236, 122, 123, 107, "Blood Assassin;Cruel Blood Assassin" },
    { 97, 28, 120, 93, "Zombie Fighter;Resurrected Gladiator" },
    { 212, 223, 122, 107, "Blood Assassin;Ash Slaughterer" },
    { 37, 204, 121, 100, "Ash Slaughterer;Resurrected Gladiator" },
    { 155, 56, 124, 111, "Burning Lava Giant;Ruthless Lava Giant" },
    { 202, 126, 123, 123, "Cruel Blood Assassin" },
    { 223, 195, 122, 107, "Blood Assassin;Ash Slaughterer" },
    { 77, 211, 121, 100, "Ash Slaughterer;Resurrected Gladiator" },
};

static const AfkSpot AFK_SPOTS_W80[] = {
    { 51, 66, 114, 111, "Crypos;Crypta" },
    { 170, 63, 103, 99, "Bone Scorpion;Venomous Chain Scorpion" },
    { 206, 34, 105, 99, "Bone Scorpion;Orcus" },
    { 225, 168, 103, 103, "Bone Scorpion" },
    { 182, 175, 105, 103, "Bone Scorpion;Orcus" },
    { 93, 112, 105, 99, "Orcus;Venomous Chain Scorpion" },
    { 209, 89, 99, 99, "Venomous Chain Scorpion" },
    { 39, 186, 111, 111, "Crypta" },
};

static const AfkSpot AFK_SPOTS_W81[] = {
    { 62, 138, 120, 105, "Condra;Gollock" },
    { 202, 166, 108, 105, "Gollock;Orcus" },
    { 78, 103, 120, 117, "Condra;Narcondra" },
    { 213, 126, 120, 105, "Narcondra;Orcus" },
    { 145, 108, 117, 117, "Condra" },
    { 131, 146, 105, 105, "Orcus" },
    { 126, 124, 117, 105, "Condra;Orcus" },
    { 187, 81, 120, 120, "Narcondra" },
};

static const AfkSpotList AFK_SPOTS[] = {
    { 0, AFK_SPOTS_W0, 8 },
    { 1, AFK_SPOTS_W1, 8 },
    { 2, AFK_SPOTS_W2, 8 },
    { 3, AFK_SPOTS_W3, 8 },
    { 4, AFK_SPOTS_W4, 8 },
    { 7, AFK_SPOTS_W7, 8 },
    { 8, AFK_SPOTS_W8, 8 },
    { 10, AFK_SPOTS_W10, 8 },
    { 33, AFK_SPOTS_W33, 8 },
    { 37, AFK_SPOTS_W37, 8 },
    { 38, AFK_SPOTS_W38, 8 },
    { 51, AFK_SPOTS_W51, 8 },
    { 56, AFK_SPOTS_W56, 8 },
    { 57, AFK_SPOTS_W57, 8 },
    { 63, AFK_SPOTS_W63, 8 },
    { 80, AFK_SPOTS_W80, 8 },
    { 81, AFK_SPOTS_W81, 8 },
};

static const int AFK_SPOTS_WORLD_COUNT = sizeof(AFK_SPOTS) / sizeof(AFK_SPOTS[0]);

inline const AfkSpotList* GetAfkSpotsForWorld(int world)
{
    for (int i = 0; i < AFK_SPOTS_WORLD_COUNT; ++i)
    {
        if (AFK_SPOTS[i].world == world)
            return &AFK_SPOTS[i];
    }
    return nullptr;
}
