// NewUIAfkSpotWindow.h: "Recommended AFK spots" for the current map.
// Clicking a row runs CMuHelper::GoAfkSpot -> town buff + potions -> warp back ->
// walk to the chosen tile -> start hunting. Data comes from AfkSpotsData.h
// (generated by MuMain/tools/gen_afk_spots_header.py from the web afkSpots.js).
#pragma once

#include "UI/NewUI/NewUIBase.h"
#include "UI/NewUI/NewUIManager.h"
#include "MUHelper/AfkSpotsData.h"

namespace SEASON3B
{
    class CNewUIAfkSpotWindow : public CNewUIObj
    {
    private:
        CNewUIManager* m_pNewUIMng;
        POINT m_Pos;
        int m_width;
        int m_height;
        int m_lineHeight;
        int m_iSelectedRow;

        const AfkSpotList* m_pSpots;  // current map's list (set in OpenningProcess)

    public:
        CNewUIAfkSpotWindow();
        virtual ~CNewUIAfkSpotWindow();

        bool Create(CNewUIManager* pNewUIMng, int x, int y);
        void Release();
        void SetPos(int x, int y);

        bool UpdateMouseEvent();
        bool UpdateKeyEvent();
        bool Update();
        bool Render();

        bool BtnProcess();

        virtual void OpenningProcess();
        void ClosingProcess();
        float GetLayerDepth();

    private:
        void RenderFrame();
    };
}
