# -*- coding: utf-8 -*-
"""
Generate MuMain/src/source/MUHelper/AfkSpotsData.h from the web client's
pre-generated MUWebClient/web/src/game/data/afkSpots.js.

This does NOT touch the database — the web generator
(MUWebClient/tools/gen_afk_spots.py) already did the MonsterSpawnArea +
TerrainData + MonsterAttribute join. We only convert its JSON output into a
static C++ table consumed by CNewUIAfkSpotWindow / CMuHelper.

Re-run after regenerating afkSpots.js:
    python D:\\games\\MuMain\\tools\\gen_afk_spots_header.py
"""
import io, json, os, re

WEB_JS = r"D:\games\MUWebClient\web\src\game\data\afkSpots.js"
OUT_H  = r"D:\games\MuMain\src\source\MUHelper\AfkSpotsData.h"


def load_spots():
    with io.open(WEB_JS, encoding="utf-8") as f:
        text = f.read()
    # strip "export const AFK_SPOTS = " prefix and trailing semicolon
    m = re.search(r"=\s*(\{.*\})\s*;?\s*$", text, re.S)
    if not m:
        raise SystemExit("could not locate JSON object in afkSpots.js")
    return json.loads(m.group(1))


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def monster_label(monsters):
    # top 2 monsters by in-circle expected count (qc), fall back to q
    ordered = sorted(monsters, key=lambda mo: mo.get("qc", mo.get("q", 0)), reverse=True)
    names = [mo.get("m", "?") for mo in ordered[:2]]
    return ";".join(names)


def main():
    data = load_spots()
    worlds = sorted(data.keys(), key=lambda k: int(k))

    lines = []
    lines.append("// AUTO-GENERATED by MuMain/tools/gen_afk_spots_header.py — do not edit by hand.")
    lines.append("// Source: MUWebClient/web/src/game/data/afkSpots.js")
    lines.append("// Regenerate: python MuMain/tools/gen_afk_spots_header.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("struct AfkSpot")
    lines.append("{")
    lines.append("    int x;")
    lines.append("    int y;")
    lines.append("    int lv;        // highest monster level in the cluster")
    lines.append("    int lvMin;     // lowest monster level in the cluster")
    lines.append("    const char* mons;  // top 2 monster names, ';'-separated (English)")
    lines.append("};")
    lines.append("")
    lines.append("struct AfkSpotList")
    lines.append("{")
    lines.append("    int world;            // ENUM_WORLD")
    lines.append("    const AfkSpot* spots;")
    lines.append("    int count;")
    lines.append("};")
    lines.append("")

    lists = []
    for w in worlds:
        spots = data[w]
        if not spots:
            continue
        arr = "AFK_SPOTS_W%s" % w
        lists.append((int(w), arr, len(spots)))
        lines.append("static const AfkSpot %s[] = {" % arr)
        for sp in spots:
            mons = c_escape(monster_label(sp.get("monsters", [])))
            lines.append(
                "    { %d, %d, %d, %d, \"%s\" },"
                % (int(sp["x"]), int(sp["y"]), int(sp.get("lv", 0)),
                   int(sp.get("lvMin", 0)), mons)
            )
        lines.append("};")
        lines.append("")

    lines.append("static const AfkSpotList AFK_SPOTS[] = {")
    for world, arr, n in lists:
        lines.append("    { %d, %s, %d }," % (world, arr, n))
    lines.append("};")
    lines.append("")
    lines.append("static const int AFK_SPOTS_WORLD_COUNT = sizeof(AFK_SPOTS) / sizeof(AFK_SPOTS[0]);")
    lines.append("")
    lines.append("inline const AfkSpotList* GetAfkSpotsForWorld(int world)")
    lines.append("{")
    lines.append("    for (int i = 0; i < AFK_SPOTS_WORLD_COUNT; ++i)")
    lines.append("    {")
    lines.append("        if (AFK_SPOTS[i].world == world)")
    lines.append("            return &AFK_SPOTS[i];")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")

    out = "\n".join(lines)
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    with io.open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print("wrote %s: %d worlds, %d spots" %
          (OUT_H, len(lists), sum(n for _, _, n in lists)))


if __name__ == "__main__":
    main()
